@startuml
skinparam monochrome true
start

:Задание начального (ключевого)\nблока информации; 
:Вычисление начального (ключевого) хэша\nпо исходному блоку информации; 
:Сохранение начального хэша\nв буферную переменную; 

'repeat
while (\nесть новая информация\nдля включения в документ?\n) is (да)
  :Добавление к документу\nнового блока информации;
  :Добавление к документу\nхэша из буферной переменной;
  :Вычисление хэша\nвсего текущего документа;
  :Сохранение полученного хэша\nв буферную переменную; 
endwhile (нет)
'repeat while (пока есть допол)
:Добавление к документу\nхэша из буферной переменной;
stop


@enduml

