@startuml
skinparam monochrome true
start

:Задание начального (ключевого) блока информации; 
:Вычисление начального (ключевого) хэша по исходному блоку информации; 
:Сохранение начального хэша\nв буферную переменную; 

'repeat
while (\nесть новая информация для включения в документ?\n) is (да)
  :Добавление к документу нового блока информации;
  :Добавление к документу хэша из буферной переменной;
  :Вычисление хэша всего текущего документа;
  :Сохранение полученного хэша в буферную переменную; 
endwhile (нет)
'repeat while (пока есть допол)
:Добавление к документу хэша из буферной переменной;
stop


@enduml

