@startuml
skinparam monochrome true

'title Верификация ПТД 

start

: Инициализация буферной переменной; 

while (\nв документе есть\nслужебное поле\nс хэш-суммой?\n) is (да)
    
: Сохранить хэш-сумму в буферную переменную;
: Удалить хэш-сумму из тела документа;

: Вычислить проверочную хэш-сумму по оставшемуся телу документа; 

if (\nпроверочная хэш-сумма совпадает\n с хэш-суммой в буферной переменной?\n ) then (да)

else (нет)

:целостность цепочки транзакций нарушена выявлена возможная фальсификация документа >
  stop

endif

'repeat while ( i < 0 )
endwhile (нет)

:целостность цепочки транзакций не нарушена документ является подлинником>



stop
@enduml
