@startuml
skinparam monochrome true

'title Верификация ПТД 

start

:Начало процедуры проверки хэшей;

:i = N;

repeat

: распаковка хэша блока i;

: расчет проверочного хэша блока i;

if (обычный и проверочный хэши) then (совпадает)

  :распаковка транзакции i;

else (не совпадает)

  :выявлена возможная фальсификация документа;
  stop

endif

:i = i - 1;

repeat while ( i < 0 )

:документ является подлинником;



stop
@enduml
