@startuml
skinparam monochrome true

title Работа на базовом уровне 

start

:Генерация исходного блока кода лицом, ответственным за выдачу документа;

:Задание начального блокчейна; 
note right: Здесь генерируется исходный хэш блока N=0

:Начало работы алгоритма;

note left: Создается блок N+1

:j = 1;

repeat
  :добавление нового блока;
  :генерация содержимого блока j;
  :добавление в запись хэша блока j-1;
  :генерация хэша j;
  :j = j + 1;
repeat while (работа окончена?)

if (нужна ли проверка целостности?) then (да)

:Начало процедуры проверки хэшей;

:i = N;

repeat

: распаковка хэша блока i;

: расчет проверочного хэша блока i;

if (обычный и проверочный хэши) then (совпадает)

  :распаковка транзакции i;

else (не совпадает)

  :выявлена возможная фальсификация документа;
  stop

endif

:i = i - 1;

repeat while ( i < 0 )

:документ является подлинником;

endif

stop

@startmath
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath

@enduml

